apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-s3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: platform/csi-s3
spec:
  project: default
  sources:
  - repoURL: https://yandex-cloud.github.io/k8s-csi-s3/charts
    chart: csi-s3
    targetRevision: '*'
    helm:
      valueFiles:
      - $values/platform/csi-s3/values.yaml
  - repoURL: https://gitea.example.com/admin/homelab.git
    targetRevision: main
    ref: values
  - repoURL: https://gitea.example.com/admin/homelab.git
    targetRevision: main
    path: platform/csi-s3
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
