apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: platform/gitea
spec:
  project: default
  sources:
  - repoURL: https://dl.gitea.com/charts
    chart: gitea
    targetRevision: '*'
    helm:
      valueFiles:
      - $values/platform/gitea/values.yaml
  - repoURL: https://gitea.example.com/admin/homelab.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
    automated:
      selfHeal: true
      prune: true
