apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.fairwinds.com/stable
    chart: goldilocks
    targetRevision: "*"
    helm:
      values: |
        vpa:
          enabled: true
        dashboard:
          enabled: true
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
        controller:
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: goldilocks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
