apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: apps/nextcloud
spec:
  project: default
  sources:
  - repoURL: https://nextcloud.github.io/helm
    chart: nextcloud
    targetRevision: '*'
    helm:
      valueFiles:
      - $values/apps/nextcloud/values.yaml
  - repoURL: https://gitea.example.com/admin/homelab.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
    automated:
      selfHeal: true
      prune: true
