apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pdbs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: platform/pdbs
spec:
  project: default
  source:
    repoURL: https://gitea.example.com/admin/homelab.git
    path: platform/pdbs
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
